blank_issues_enabled: false
contact_links:
  - name: Dúvidas gerais
    url: https://github.com/fcte-pi1/2026_1_PI1_Grupo02_Juliana/discussions
    about: Use as discussões para dúvidas e alinhamentos gerais.
