# Generated by Django 6.0.4 on 2026-05-24 03:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labirinto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('dimensao', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(32)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Micromouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('algoritmo', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tempo_inicio', models.DateTimeField(blank=True, null=True)),
                ('tempo_fim', models.DateTimeField(blank=True, null=True)),
                ('consumo_bateria', models.FloatField(blank=True, null=True)),
                ('velocidade_media', models.FloatField(blank=True, null=True)),
                ('sucesso', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_curso', 'Em curso'), ('finalizada', 'Finalizada'), ('abortada', 'Abortada')], default='em_curso', max_length=12)),
                ('maze', models.JSONField(blank=True, default=dict)),
                ('pose', models.JSONField(blank=True, default=dict)),
                ('labirinto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='runs.labirinto')),
                ('micromouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='runs.micromouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordenada_x', models.IntegerField()),
                ('coordenada_y', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('passo', models.PositiveIntegerField(default=0)),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='runs.tentativa')),
            ],
            options={
                'ordering': ['passo'],
            },
        ),
    ]
