# Generated by Django 6.0.4 on 2026-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='bateria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posicao',
            name='orientacao',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='posicao',
            name='velocidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
